import { useState } from 'react'
import { ArrowUpRight, BrainCircuit, ChevronRight } from 'lucide-react'
import { useCurrentFrame, useMission } from '../stores/mission'
import { componentNames, formatNumber, percent } from '../services/api'
import type { Decision } from '../types'
import { EmptyState, Panel } from './ui'

export function ScoreBreakdown({ components }: { components: Record<string, number> }) {
  const max = Math.max(0.2, ...Object.values(components).map(Math.abs))
  return <div className="score-breakdown">{Object.entries(components).map(([key, value]) => <div className="score-row" key={key}><span>{componentNames[key] ?? key}</span><div className="score-track"><div className={value < 0 ? 'negative' : key === 'uncertainty' || key === 'information' ? 'violet-fill' : ''} style={{ width: `${Math.abs(value) / max * 100}%` }} /></div><span className={`mono ${value < 0 ? 'orange-text' : ''}`}>{value >= 0 ? '+' : ''}{value.toFixed(3)}</span></div>)}</div>
}

export function DecisionPanel({ decision: supplied, compact = false }: { decision?: Decision; compact?: boolean }) {
  const frame = useCurrentFrame()
  const decision = supplied ?? frame?.policies.magnts?.decision
  const [alternative, setAlternative] = useState<number | null>(null)
  const inspected = decision?.candidates.find(c => c.start === alternative)
  const openTrace = useMission(s => s.openTrace)
  return <Panel className={`decision-panel ${compact ? 'compact' : ''}`} title="Why this window?" eyebrow="DECISION INTELLIGENCE" action={<BrainCircuit size={19} className="accent" />}>
    {decision ? <>
      <div className="decision-selected"><div className="decision-target"><span className="eyebrow">{inspected && !inspected.selected ? 'REJECTED CANDIDATE' : 'SELECTED WINDOW'}</span><strong>B{String(inspected?.start ?? decision.action.start).padStart(2, '0')}<span> — B{String((inspected?.start ?? decision.action.start) + decision.action.width - 1).padStart(2, '0')}</span></strong></div><div className="decision-score"><span>Total value</span><strong className="mono">{formatNumber(inspected?.score ?? decision.score, 3)}</strong></div></div>
      {!inspected && <div className="decision-reasons">{decision.reasons.slice(0, 2).map(reason => <span key={reason}><ChevronRight size={12} />{reason}</span>)}</div>}
      <ScoreBreakdown components={inspected?.components ?? decision.components} />
      {!compact && <div className="alternatives"><div className="eyebrow">CANDIDATE WINDOWS <span>p(active) / value</span></div>{decision.candidates.slice(0, 4).map(candidate => <button className={candidate.selected ? 'chosen' : ''} key={candidate.start} onClick={() => setAlternative(candidate.selected ? null : candidate.start)}><span>B{candidate.start.toString().padStart(2, '0')}–{candidate.end.toString().padStart(2, '0')}{candidate.selected && <small>SELECTED</small>}</span><span>{percent(candidate.probability, 0)}<strong>{candidate.score.toFixed(3)}</strong><ChevronRight size={13} /></span></button>)}</div>}
      <button className="decision-trace-link" onClick={() => void openTrace()}>Inspect the complete decision <ArrowUpRight size={14} /></button>
    </> : <EmptyState title="Intelligence starts with an observation" description="Every score and explanation is generated by the active policy. Run an experiment to inspect its reasoning." action={false} />}
  </Panel>
}
