import { useEffect, useState } from 'react'
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { ArrowRight, ArrowUpRight, Check, ChevronRight, Copy, Database, Download, FileCheck2, Fingerprint, LockKeyhole, Play, RefreshCw } from 'lucide-react'
import { useMission } from '../stores/mission'
import { api, formatNumber } from '../services/api'
import type { DatasetPreview } from '../types'
import { EmptyState, Metric, PageHeader, Panel, SourceBadge } from '../components/ui'
import { MatrixCanvas } from '../visualizations/MatrixCanvas'

export function Provenance() {
  const { datasets, navigate, bootstrap } = useMission()
  const [copied, setCopied] = useState<string | null>(null)
  return <>
    <PageHeader eyebrow="SCIENTIFIC INTEGRITY" title="Data Integrity & Provenance" description="Three distinct data categories. An explicit origin, transformation history, and evaluation scope for each." action={<button className="button secondary" onClick={() => void bootstrap()}><RefreshCw size={14} />Refresh catalog</button>} />
    <div className="provenance-intro"><Fingerprint size={25} className="accent" /><div><strong>Every claim has a source.</strong><p>Synthetic radar data, controlled simulation, and real measured RF are distinct throughout the experiment pipeline. Dataset identity travels with every result.</p></div></div>
    <div className="provenance-grid">{datasets.map(dataset => <Panel key={dataset.id} className="provenance-card"><div className="provenance-card-heading"><div className={`dataset-icon ${dataset.category === 'REAL_MEASURED_RF' ? 'violet-text' : ''}`}>{dataset.status === 'available' ? <Database size={23} strokeWidth={1.5} /> : <LockKeyhole size={22} strokeWidth={1.5} />}</div><SourceBadge category={dataset.category} /></div><h2>{dataset.name}</h2><p className="dataset-org">{dataset.organization}</p><span className={`availability ${dataset.status === 'available' ? 'accent' : 'orange-text'}`}>{dataset.status === 'available' ? <Check size={13} /> : <LockKeyhole size={12} />}{dataset.status?.replaceAll('_', ' ').toUpperCase()}</span><p className="dataset-note">{dataset.note}</p>
      <dl className="dataset-details"><div><dt>Original format</dt><dd>{dataset.original_format}</dd></div><div><dt>Evaluation truth</dt><dd>{dataset.ground_truth === null ? 'Not installed' : dataset.ground_truth ? 'Available · synthetic / controlled' : 'No labelled emitter ground truth'}</dd></div><div><dt>Source samples</dt><dd>{dataset.id === 'simulation' ? 'Generated from recorded configuration' : formatNumber(dataset.source_sample_count ?? dataset.sample_count)}</dd></div>{dataset.frequency_range_mhz && <div><dt>Frequency range</dt><dd>{dataset.frequency_range_mhz.map(v => formatNumber(v, 2)).join('–')} MHz</dd></div>}{dataset.time_start_utc && <div><dt>Observation UTC</dt><dd>{dataset.time_start_utc}</dd></div>}{dataset.ingested_at && <div><dt>Ingested UTC</dt><dd>{dataset.ingested_at.replace('T', ' ').slice(0, 19)}</dd></div>}{dataset.artifact && <div><dt>Local artifact</dt><dd className="mono break-all">{dataset.artifact}</dd></div>}</dl>
      {dataset.source_sha256 && <details className="checksum-details"><summary><FileCheck2 size={14} />Source & artifact checksums <ChevronRight size={13} /></summary><span className="eyebrow">SOURCE SHA-256</span><code>{dataset.source_sha256}</code><span className="eyebrow">ARTIFACT SHA-256</span><code>{dataset.artifact_sha256}</code></details>}
      <details className="lineage-details"><summary>Preprocessing lineage <ChevronRight size={13} /></summary><ol>{dataset.lineage?.map((step, i) => <li key={step}><span>{String(i + 1).padStart(2, '0')}</span>{step}</li>)}</ol>{dataset.preprocessing && <pre>{JSON.stringify(dataset.preprocessing, null, 2)}</pre>}</details>
      {dataset.install_command && <div className="install-command"><code>{dataset.install_command}</code><button aria-label={`Copy install command for ${dataset.name}`} className="icon-button" onClick={() => { void navigator.clipboard.writeText(dataset.install_command!).then(() => setCopied(dataset.id)).catch(() => setCopied(null)) }}>{copied === dataset.id ? <Check size={14} /> : <Copy size={14} />}</button></div>}
      <div className="provenance-actions">{dataset.source_url && <a href={dataset.source_url} target="_blank" rel="noreferrer" className="text-button">Publisher source <ArrowUpRight size={13} /></a>}{dataset.status === 'available' && dataset.id !== 'simulation' && <button className="text-button accent" onClick={() => navigate('explorer')}>Inspect artifact <ArrowRight size={13} /></button>}{dataset.id === 'simulation' && <button className="text-button accent" onClick={() => navigate('command')}>Configure environment <ArrowRight size={13} /></button>}</div>
    </Panel>)}</div>
    <Panel title="Truth and measurement are different capabilities" eyebrow="EVALUATION SCOPE"><div className="table-scroll"><table className="data-table"><thead><tr><th>Source</th><th>Measured signal?</th><th>Labelled truth?</th><th>Purpose</th></tr></thead><tbody><tr><td>Turing synthetic radar</td><td>No · simulated PDWs</td><td>Retained stare-mode pulse occupancy</td><td>Dataset-aligned controlled evaluation</td></tr><tr><td>e-CALLISTO</td><td>Yes · solar radio spectrum</td><td>No EW emitter labels</td><td>Ingestion, robustness, adaptive region prioritization</td></tr><tr><td>Controlled simulation</td><td>No · seeded model</td><td>Complete within simulator assumptions</td><td>Fair duels, ablations, timing and change experiments</td></tr></tbody></table></div></Panel>
  </>
}

export function DataExplorer() {
  const s = useMission()
  const available = s.datasets.filter(d => d.id !== 'simulation' && d.status === 'available')
  const [selected, setSelected] = useState('')
  const id = selected || available.find(d => d.category === 'OFFICIAL_SYNTHETIC_RADAR')?.id || available[0]?.id
  const [data, setData] = useState<DatasetPreview | null>(null), [error, setError] = useState('')
  useEffect(() => {
    if (!id) return
    let active = true; setData(null); setError('')
    void api<DatasetPreview>(`/api/datasets/${id}/preview`).then(value => { if (active) setData(value) }).catch(e => { if (active) setError(e instanceof Error ? e.message : String(e)) })
    return () => { active = false }
  }, [id])
  const measured = data?.metadata.category === 'REAL_MEASURED_RF'
  const profile = data?.frequency_mhz.map((f, b) => { const values = data.intensity.map(row => row[b]).filter((v): v is number => v !== null); return { frequency: +f.toFixed(2), intensity: values.length ? values.reduce((a, b) => a + b, 0) / values.length : null } }) ?? []
  const overTime = data?.intensity.map((row, i) => { const values = row.filter((v): v is number => v !== null); return { time: +(data.time_ms[i] / 1000).toFixed(1), intensity: values.length ? values.reduce((a, b) => a + b, 0) / values.length : null } }) ?? []
  return <>
    <PageHeader eyebrow="DATASET INSPECTION" title="Dataset Explorer" description="Inspect the processed recording, its physical coordinates, and original sample features." action={<button className="button secondary" onClick={() => s.navigate('provenance')}><Fingerprint size={14} />Data provenance</button>} />
    {!s.engine ? <Panel><EmptyState title="Loading the local data catalog" description="Waiting for the local engine to verify available artifacts and their provenance." action={false} /></Panel> : !available.length ? <Panel><EmptyState title="No public dataset artifact is installed" description="The simulator remains available. Use Data Provenance for the e-CALLISTO download command and the authorized TSRD importer." action={false} /></Panel> : <>
      <div className="dataset-selector"><label className="field"><span>Local processed artifact</span><select aria-label="Dataset artifact" value={id} onChange={e => setSelected(e.target.value)}>{available.map(d => <option key={d.id} value={d.id}>{d.name}</option>)}</select></label><SourceBadge category={data?.metadata.category} /><div className="transport-spacer" />{id && <a href={`/api/datasets/${id}/export?format=npz`} className="button secondary small"><Download size={13} />NPZ</a>}<button className="button primary small" disabled={!data || s.busy} onClick={() => { if (data) void s.start({ ...s.config, dataset_id: data.metadata.id, algorithms: ['fixed', 'magnts'] }, 'duel') }}><Play size={13} />RUN RECEIVER REPLAY</button></div>
      {error ? <div className="error-banner">{error}</div> : !data ? <Panel><EmptyState title="Loading bounded artifact preview" description="Verifying the local checksum and preparing time-frequency samples…" action={false} /></Panel> : <>
        <div className={measured ? 'measured-banner' : 'note-box'}>{data.metadata.note}</div>
        <div className="metric-cards"><Panel><Metric label={measured ? 'Measured samples' : 'Retained pulse samples'} value={formatNumber(data.metadata.source_sample_count)} detail={data.metadata.original_format} /></Panel><Panel><Metric label="Frequency span" value={data.metadata.frequency_range_mhz?.map(f => formatNumber(f, 1)).join('–')} unit="MHz" /></Panel><Panel><Metric label="Recording duration" value={formatNumber((data.time_ms.at(-1) ?? 0) / 1000, 1)} unit="s" detail="Original coordinate interval" /></Panel><Panel><Metric label={measured ? 'Recording station' : 'Receiver mode'} value={measured ? data.metadata.station : data.metadata.name.includes('stare') ? 'Stare' : 'Scan'} detail={data.metadata.time_start_utc?.slice(0, 10)} /></Panel></div>
        <Panel title={measured ? 'Measured RF spectrum' : 'PDW-derived time-frequency structure'} eyebrow="BOUNDED PREVIEW · ORIGINAL UNITS" action={<span className="mono small-copy muted">{data.metadata.energy_unit}</span>}><MatrixCanvas data={data.intensity} times={data.time_ms} frequencies={data.frequency_mhz} range={data.display_range} /><div className="chart-legend"><span><i className="legend-dot violet" />Recorded intensity</span><span><i className="legend-dot dark" />Missing data</span><span className="legend-hint">{data.intensity.length} × {data.frequency_mhz.length} preview</span></div><p className="method-note">{data.downsampling} Axis ticks use the selected channel coordinates; irregular channels are retained in the downloadable artifact.</p></Panel>
        <div className="two-column"><Panel title="Frequency profile" eyebrow="MEAN INTENSITY · PREVIEW SAMPLES"><DataChart data={profile} x="frequency" unit="MHz" /></Panel><Panel title="Activity over time" eyebrow="MEAN INTENSITY · PREVIEW SAMPLES"><DataChart data={overTime} x="time" unit="s" /></Panel></div>
        <Panel title={measured ? 'Standardized measured samples' : 'Pulse Descriptor Word samples'} eyebrow="RAW FEATURES PRESERVED FOR AUDIT" action={<a href={`/api/datasets/${id}/export?format=parquet`} className="text-button"><Download size={13} />Download Parquet</a>}><div className="table-scroll"><table className="data-table"><thead><tr>{Object.keys(data.samples[0] ?? {}).map(key => <th key={key}>{key.replaceAll('_', ' ')}</th>)}</tr></thead><tbody>{data.samples.map((sample, i) => <tr key={i}>{Object.values(sample).map((value, j) => <td className="mono" key={j}>{typeof value === 'number' ? formatNumber(value, Math.abs(value) < 1 ? 6 : 3) : value ?? '—'}</td>)}</tr>)}</tbody></table></div></Panel>
      </>}
    </>}
  </>
}

function DataChart({ data, x, unit }: { data: Record<string, number | null>[]; x: string; unit: string }) {
  return <div className="data-chart"><ResponsiveContainer width="100%" height={195} minWidth={1}><AreaChart data={data} margin={{ left: -16, right: 22, top: 15 }}><CartesianGrid stroke="#252e3b" strokeDasharray="3 5" vertical={false} /><XAxis dataKey={x} minTickGap={45} tick={{ fill: '#8a96a8', fontSize: 10 }} tickFormatter={v => `${v}${unit}`} axisLine={false} tickLine={false} /><YAxis tick={{ fill: '#8a96a8', fontSize: 10 }} axisLine={false} tickLine={false} /><Tooltip contentStyle={{ background: '#171d28', border: '1px solid #303a49', borderRadius: 8, fontSize: 12 }} /><Area type="monotone" dataKey="intensity" stroke="#a894d4" fill="#a894d4" fillOpacity={0.1} dot={false} isAnimationActive={false} connectNulls={false} /></AreaChart></ResponsiveContainer></div>
}
