import { BookOpen, Download, FlaskConical, Info, ShieldCheck } from 'lucide-react'
import { useCurrentFrame, useMission } from '../stores/mission'
import { formatNumber, percent } from '../services/api'
import { PageHeader, Panel, TruthBoundary } from '../components/ui'

export function Methodology() {
  const s = useMission()
  const frame = useCurrentFrame()
  return <>
    <PageHeader eyebrow="RESEARCH NOTES" title="Methodology & limitations" description="Explicit definitions, fair comparisons, and a clear boundary between software evidence and field validation." action={s.run && <a className="button secondary" href={`/api/experiment/${s.run.id}/export?format=json`}><Download size={14} />Export this experiment</a>} />
    <div className="three-column methodology-overview"><Panel><ShieldCheck size={22} className="accent" /><h3>Observation-only learning</h3><p>The policy receives public receiver geometry and frozen, selected-band observations. It never receives environment truth, scenario parameters, source labels, or future energy.</p></Panel><Panel><FlaskConical size={22} className="violet-text" /><h3>Paired evaluation</h3><p>Each duel shares the exact same immutable world, seeded detector random fields, receiver limits, and horizon. Every policy begins with independent uninformative beliefs.</p></Panel><Panel><BookOpen size={22} /><h3>Trace-derived evidence</h3><p>Metrics come from recorded actions, observations, pre-observation predictions, and evaluation labels. An undefined denominator produces N/A, never a fabricated zero.</p></Panel></div>
    <Panel title="Metric definitions & current values" eyebrow="SIH METRICS · DENOMINATORS MATTER" action={<Info size={17} />}><div className="table-scroll"><table className="data-table methodology-table"><thead><tr><th>Metric</th><th>Definition & scope</th><th>Fixed Sweep</th><th>AAMS-X</th></tr></thead><tbody>{s.methodology.map(metric => {
      const render = (algorithm: 'fixed' | 'magnts') => { const value = frame?.policies[algorithm]?.metrics[metric.key]; return typeof value !== 'number' ? 'N/A' : metric.unit === 'fraction' ? percent(value) : `${formatNumber(value, metric.unit === 'ms' ? 1 : 3)}${metric.unit === 'ms' ? ' ms' : ''}` }
      return <tr key={metric.key}><td><strong>{metric.name}</strong><small>{metric.truth ? 'Requires labelled truth' : 'Observation-only metric'}</small></td><td><code>{metric.formula}</code><p>{metric.note}</p></td><td className="mono">{render('fixed')}</td><td className="mono accent">{render('magnts')}</td></tr>
    })}</tbody></table></div><p className="method-note">TP/FP/TN/FN refer to valid observed cells, except global recall and miss rate, which also count unobserved active cells. Interception episodes are contiguous activity in one logical band, not classified emitters. Confidence intervals are across independent seeds.</p></Panel>
    <div className="two-column"><Panel title="Limitations" eyebrow="WHAT THESE RESULTS DO AND DO NOT ESTABLISH"><ul className="research-list"><li><strong>Environment assumptions matter.</strong> The simulator is an abstract occupancy and energy model, not a validated propagation, antenna, or receiver hardware model.</li><li><strong>Public measured RF has no EW emitter labels.</strong> e-CALLISTO records solar radio spectrum. Detection probability, false-alarm rate, emitter interception, and truth-based reward are N/A in this mode.</li><li><strong>Official radar data is synthetic.</strong> Stare-mode occupancy describes retained source pulses; scan-mode data is already censored and cannot justify full-spectrum negative labels.</li><li><strong>MAG-NTS is a research composition.</strong> Weighted scores and recurrence confidence are heuristics. Information gain is exact for the assumed Beta-Bernoulli model; the overall scheduler has no optimality proof.</li><li><strong>Unpredictability imposes limits.</strong> A randomized frequency source may be no more interceptable than the instantaneous bandwidth fraction. Adaptive methods need exploitable structure.</li><li><strong>Timing metrics are censored.</strong> Average delay considers intercepted episodes only. Always read it with interception ratio and the missed/censored episode fraction.</li><li><strong>Partial observations can alias periodicity.</strong> Recurrence estimates can be tentative or wrong. Prospective prediction error is measured after the next actual event.</li><li><strong>No operational field validation.</strong> Public and simulated dataset results are software research evidence, not a claim of field readiness.</li></ul></Panel>
    <div className="stack"><Panel title="What exactly is the machine learning?" eyebrow="JUDGE QUESTIONS"><div className="faq-list"><details open><summary>What learns online?</summary><p>Occupancy posteriors, uncertainty, observation-pattern memory, change statistics, and recurrence estimates update from each valid selected-window observation.</p></details><details><summary>Why Thompson sampling instead of a deep network?</summary><p>This is sequential decision-making under partial observation. A probabilistic policy supports cold starts, uncertainty-driven exploration, low computational overhead, and visible decision explanations. A deep network is not required to make the scheduler adaptive.</p></details><details><summary>How do you know the added modules help?</summary><p>The Benchmark Lab runs full MAG-NTS, component ablations, vanilla Thompson sampling, and fixed sweep across paired consecutive seeds. Modules may help under suitable dynamics and add unnecessary exploration in stable conditions.</p></details><details><summary>Can the scheduler access the truth?</summary><p>The runner owns environments and evaluators; the policy constructor receives only PublicReceiver and an independent RNG seed. The POLICY_TRUTH_LEAK_TEST checks dependency restrictions, frozen payload fields, and counterfactual observation noninterference. This is an architectural boundary, not an adversarial Python sandbox.</p></details><details><summary>What happens after an unexpected change?</summary><p>A CUSUM shift can be detected only once the receiver observes contradictory evidence. The affected band’s posterior is softened and change priority temporarily increases. Unvisited changes cannot be known instantly.</p></details></div></Panel><Panel title="Research progression" eyebrow="FUTURE WORK"><ol className="future-list"><li>Live SDR ingestion and hardware-in-the-loop evaluation</li><li>Calibrated receiver probability and retuning models</li><li>Multi-receiver cooperative active sensing</li><li>Richer partially observable and context-aware policies</li><li>Expanded measured datasets and long-duration adaptation</li><li>Edge inference and decentralized sensing experiments</li></ol></Panel></div></div>
    <TruthBoundary />
  </>
}
