import { useState } from 'react'
import { ArrowRight, Clock3, Radio, Timer, Waves } from 'lucide-react'
import { useCurrentFrame, useMission } from '../stores/mission'
import { formatNumber, percent } from '../services/api'
import { TransportBar } from '../components/Controls'
import { EmptyState, Metric, PageHeader, Panel, TruthBoundary } from '../components/ui'
import { Waterfall, WaterfallLegend } from '../visualizations/Waterfall'
import { useVisibleFrames } from '../hooks/useVisibleFrames'

export function Periodic() {
  const s = useMission()
  const frame = useCurrentFrame()
  const frames = useVisibleFrames()
  const p = frame?.policies.magnts
  const candidates = p?.belief.periodicity ?? []
  const [band, setBand] = useState<number | null>(null)
  const candidate = candidates.find(c => c.band === band) ?? candidates[0]
  const receiver = s.run?.config.receiver ?? s.config.receiver
  const predictions = frames.flatMap(f => f.policies.magnts?.evaluation?.prediction_events ?? []).filter(p => !candidate || p.band === candidate.band).slice(-8).reverse()
  const actualEvents = candidate && s.judge ? frames.filter((f, i) => f.evaluation?.active_bands?.includes(candidate.band) && !frames[i - 1]?.evaluation?.active_bands?.includes(candidate.band)).map(f => f.step) : []
  const timelineSpan = Math.max(s.run?.config.horizon ?? 420, candidate?.next_slot ?? 0)
  return <>
    <PageHeader eyebrow="TEMPORAL INTELLIGENCE" title="Periodic Intercept Challenge" description="Unknown recurrence. Partial observations. Learn an approximate next listening opportunity." action={<button className="button primary" disabled={s.busy || !s.engine} onClick={() => { setBand(null); void s.start({ ...s.config, scenario: 'periodic', dataset_id: 'simulation', horizon: 420, emitters: null, receiver: { ...s.config.receiver, bands: 32, window_width: 4, slot_ms: 100, min_dwell_ms: 10, retune_ms: 8, scan_latency_ms: 1 }, algorithms: ['fixed', 'magnts'] }, 'periodic') }}><Timer size={16} />START PERIODIC CHALLENGE</button>} />
    <div className="periodic-intro"><div className="periodic-symbol"><Waves size={34} strokeWidth={1.2} /></div><div><h3>Recognize a rhythm. Anticipate a return.</h3><p>MAG-NTS fits recurrence from separated observed episodes, tolerates skipped cycles, and tests phase consistency against observed misses. A prediction is soft evidence, not certainty.</p></div><span className="badge violet">4+ OBSERVED EPISODES REQUIRED</span></div>
    <TransportBar />
    <div className="metric-cards"><Panel><Metric label="Estimated period" value={candidate ? formatNumber(candidate.period_slots * receiver.slot_ms / 1000, 2) : '—'} unit="s" detail={candidate ? `${candidate.period_slots} slots · band ${candidate.band}` : 'Waiting for sufficient evidence'} accent /></Panel><Panel><Metric label="Period confidence" value={percent(candidate?.confidence)} detail={candidate ? `${candidate.status} · phase-fit evidence` : 'No unsupported recurrence claims'} /></Panel><Panel><Metric label="Observed episodes" value={candidate?.evidence_count ?? '—'} detail="Adjacent hits merged into one episode" /></Panel><Panel><Metric label="Prediction time MAE" value={formatNumber(p?.metrics.avg_intercept_time_error_ms, 0)} unit="ms" detail={`${formatNumber(p?.metrics.resolved_predictions)} resolved prospective forecasts`} /></Panel></div>
    <div className="two-column"><Panel title="Observed spectrum and recurrence" eyebrow="THE POLICY MUST DISCOVER THE PATTERN"><Waterfall height={300} /><WaterfallLegend /></Panel><Panel title="Recurrence candidates" eyebrow="OBSERVATION-DERIVED EVIDENCE" action={<Clock3 size={18} className="violet-text" />}>{candidates.length ? <div className="period-candidates">{candidates.slice(0, 8).map(c => <button className={c.band === candidate?.band ? 'selected' : ''} key={c.band} onClick={() => setBand(c.band)}><div><strong>B{c.band.toString().padStart(2, '0')}</strong><span>{c.evidence_count} episodes</span></div><div><strong>{c.period_slots} slots</strong><span>{percent(c.confidence)} confidence</span></div><span className={`badge ${c.status === 'supported' ? 'green' : 'violet'}`}>{c.status.toUpperCase()}</span></button>)}</div> : <EmptyState title="Listening for recurrence" description="A candidate appears only after enough separated events span at least three possible cycles. Explore first, then predict." action={false} />}</Panel></div>
    <Panel title="From observed events to a prospective forecast" eyebrow="TIME-ALIGNED EVIDENCE" action={candidate && <span className="badge green">BAND {candidate.band}</span>}>
      {candidate ? <><div className="period-timeline"><div className="period-track-label">OBSERVED EVENTS</div><div className="period-track">{candidate.observed_events.map(t => <span key={t} className="observed-event" title={`Observed event at slot ${t}`} style={{ left: `${t / timelineSpan * 100}%` }} />)}<span className="time-cursor" style={{ left: `${(frame?.step ?? 0) / timelineSpan * 100}%` }} /></div><div className="period-track-label">PREDICTED NEXT</div><div className="period-track"><span className="predicted-event" style={{ left: `${candidate.next_slot / timelineSpan * 100}%` }}><Clock3 size={15} /></span></div><div className="period-track-label">ACTUAL ACTIVITY</div><div className="period-track">{s.judge ? actualEvents.map(t => <span key={t} className="actual-event" style={{ left: `${t / timelineSpan * 100}%` }} />) : <span className="muted small-copy">Hidden · enable Judge View to compare actual onsets</span>}</div></div><div className="prediction-summary"><div><span className="eyebrow">EVENT TIMESTAMPS / SLOTS</span><p className="mono">{candidate.observed_events.join(' · ')}</p></div><ArrowRight size={20} /><div><span className="eyebrow">NEXT LIKELY OPPORTUNITY</span><strong className="accent mono">Slot {candidate.next_slot.toFixed(1)} <small>({(candidate.next_slot * receiver.slot_ms / 1000).toFixed(2)} s)</small></strong></div></div></> : <div className="note-box"><Radio size={19} /><span>No recurrence estimate is available yet. The challenge begins with weak, uninformative priors.</span></div>}
    </Panel>
    <Panel title="Prospective forecast audit" eyebrow="ISSUED BEFORE THE ACTUAL EVENT"><div className="table-scroll"><table className="data-table"><thead><tr><th>Band</th><th>Forecast issued</th><th>Predicted opportunity</th><th>Actual next event</th><th>Absolute error</th><th>Confidence</th></tr></thead><tbody>{predictions.map((p, i) => <tr key={i}><td>B{p.band}</td><td>Slot {p.issued_slot}</td><td>Slot {p.predicted_slot.toFixed(1)}</td><td>Slot {p.actual_slot}</td><td>{p.error_ms.toFixed(0)} ms</td><td>{percent(p.confidence)}</td></tr>)}</tbody></table></div>{!predictions.length && <p className="note-box">{s.judge ? 'No resolved, sufficiently confident forecast yet. Errors are calculated only after the next actual onset occurs.' : 'Enable Judge View to inspect the labelled event audit. Aggregate forecast error remains available above.'}</p>}</Panel>
    <div className="note-box">Partial observation can alias periods or miss short bursts. Confidence here is a heuristic phase-fit score, not a calibrated probability that the next emission will occur.</div><TruthBoundary />
  </>
}
