"""Report generation and retrieval."""

from __future__ import annotations

from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse

from aamsx.api.schemas import ReportRequest
from aamsx.config import get_settings
from aamsx.reports.html import render

router = APIRouter(prefix="/reports", tags=["reports"])


@router.post("", status_code=201)
def create(request: ReportRequest) -> dict[str, object]:
    """Render a self-contained HTML report from stored experiment traces."""
    try:
        path = render(request.experiment_ids, title=request.title, notes=request.notes)
    except (OSError, ValueError) as exc:
        raise HTTPException(status_code=500, detail=f"report generation failed: {exc}") from exc
    return {
        "name": path.name,
        "path": str(path),
        "url": f"/api/reports/{path.name}",
        "size_bytes": path.stat().st_size,
        "experiment_ids": request.experiment_ids,
    }


@router.get("")
def listing() -> dict[str, object]:
    settings = get_settings()
    files = sorted(
        settings.reports_dir.glob("aamsx-report-*.html"),
        key=lambda path: path.stat().st_mtime,
        reverse=True,
    )
    return {
        "reports": [
            {
                "name": path.name,
                "url": f"/api/reports/{path.name}",
                "size_bytes": path.stat().st_size,
                "modified": path.stat().st_mtime,
            }
            for path in files[:50]
        ]
    }


@router.get("/{name}")
def fetch(name: str) -> FileResponse:
    settings = get_settings()
    # Reports are named by the server; refuse anything that is not one of ours so a
    # crafted name cannot walk out of the reports directory.
    if not name.startswith("aamsx-report-") or not name.endswith(".html") or "/" in name:
        raise HTTPException(status_code=400, detail="not a report name generated by AAMS-X")
    path = settings.reports_dir / name
    if not path.is_file():
        raise HTTPException(status_code=404, detail=f"no report {name!r}")
    return FileResponse(path, media_type="text/html")
