"""Generate honest offline replay artifacts and multi-seed benchmark evidence.

Run from the repository root: .venv/bin/python scripts/prepare_demo.py --benchmark
All displayed results are computed here by the same engine used for live runs.
"""

import argparse
import gzip
import json
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from backend.contracts import ExperimentConfig, ReceiverConfig  # noqa: E402
from backend.datasets.catalog import PROCESSED, catalog  # noqa: E402
from backend.datasets.environment import build_world  # noqa: E402
from backend.environment.scenarios import SCENARIOS  # noqa: E402
from backend.experiments import Experiment, Registry  # noqa: E402
from backend.experiments.benchmark import Benchmark, BenchmarkConfig  # noqa: E402
from backend.experiments.engine import canonical_json  # noqa: E402


def bundle_benchmarks(directory: Path, registry: Registry):
    destination = directory / "benchmark-traces"
    destination.mkdir(exist_ok=True)
    for path in registry.directory.glob("BENCH-*.json"):
        report = json.loads(path.read_text())
        shutil.copy2(path, directory / path.name)
        for result in report["results"]:
            source = registry.directory / f"{result['experiment_id']}.json.gz"
            if source.exists():
                shutil.copy2(source, destination / source.name)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--benchmark", action="store_true", help="Also evaluate all 10 presets across 3 consecutive seeds and 6 ablation policies")
    parser.add_argument("--bundle-existing", action="store_true", help="Package existing benchmark reports and their exact replay traces without rerunning them")
    args = parser.parse_args()
    directory = ROOT / "data" / "demo"
    directory.mkdir(parents=True, exist_ok=True)
    registry = Registry()
    if args.bundle_existing:
        bundle_benchmarks(directory, registry)
        print("Existing benchmark reports and exact traces packaged for offline replay.")
        return
    index = {"note": "Recorded reproducible experiment replay; generated by the live engine. Not a live stream.", "recordings": []}
    configurations = [
        ExperimentConfig(scenario="sudden", seed=42, horizon=360),
        ExperimentConfig(scenario="periodic", seed=42, horizon=420, receiver=ReceiverConfig(bands=32, window_width=4)),
        ExperimentConfig(scenario="agile", seed=43, horizon=360),
    ]
    included_categories = set()
    for dataset in catalog():
        if dataset["category"] in {"REAL_MEASURED_RF", "OFFICIAL_SYNTHETIC_RADAR"} and dataset["status"] == "available" and dataset["category"] not in included_categories:
            included_categories.add(dataset["category"])
            configurations.append(ExperimentConfig(dataset_id=dataset["id"], seed=42, horizon=240))
            bundled = directory / "datasets"
            bundled.mkdir(exist_ok=True)
            for suffix in [".json", ".npz", ".parquet"]:
                shutil.copy2(PROCESSED / f"{dataset['id']}{suffix}", bundled)
            raw = ROOT / "data" / "raw" / dataset["source_file"]
            if raw.exists():
                shutil.copy2(raw, bundled)
    for config in configurations:
        effective, world = build_world(config)
        experiment = Experiment(effective, world).run()
        record = experiment.record()
        registry.save(record)
        name = f"{config.scenario if config.dataset_id == 'simulation' else 'measured-rf' if world.metadata['category'] == 'REAL_MEASURED_RF' else 'official-radar'}-seed-{config.seed}.json.gz"
        (directory / name).write_bytes(gzip.compress(canonical_json(record).encode(), mtime=0))
        index["recordings"].append({"id": experiment.id, "file": name, "seed": config.seed, "scenario": config.scenario, "category": world.metadata["category"], "environment_hash": experiment.environment_hash, "trace_hash": record["trace_hash"]})
        print(f"Recorded {experiment.id} · {name} · source {world.metadata['category']}", flush=True)
        for algorithm, metrics in record["metrics"].items():
            print(f"  {algorithm}: recall={metrics['recall']}, Pd={metrics['pd']}, reward/cost={metrics['reward_cost']}", flush=True)
    if args.benchmark:
        job = Benchmark(BenchmarkConfig(scenarios=[s["id"] for s in SCENARIOS], runs=3, seed=42, horizon=240), registry)
        for scenario in job.config.scenarios:
            for seed in range(job.config.seed, job.config.seed + job.config.runs):
                job.run_one(scenario, seed)
                print(f"Benchmark {job.completed}/{job.total}: {scenario}, seed {seed}", flush=True)
        job.state = "completed"
        job.persist()
        (directory / f"{job.id}.json").write_text(canonical_json(job.snapshot()))
        index["benchmark"] = {"id": job.id, "worlds": job.total, "policy_evaluations": job.total * len(job.config.algorithms), "seeds": [42, 43, 44], "horizon": job.config.horizon}
        bundle_benchmarks(directory, registry)
    (directory / "manifest.json").write_text(json.dumps(index, indent=2))
    print("Offline demo artifacts generated. TSRD is included only after an authorized source import.")


if __name__ == "__main__":
    main()
