import { expect, test } from '@playwright/test'

test('workspace search supports keyboard navigation, empty results, and focus return', async ({ page }) => {
  await page.goto('/')
  const trigger = page.getByRole('button', { name: 'Search workspace', exact: true })
  await trigger.click()
  await expect(page.getByRole('dialog', { name: 'Search workspace' })).toBeVisible()
  const search = page.getByRole('combobox', { name: 'Search pages' })
  await expect(search).toBeFocused()
  await search.fill('nothing matches this')
  await expect(page.getByText('No matching pages', { exact: true })).toBeVisible()
  await search.fill('replay')
  await search.press('ArrowDown')
  await search.press('Enter')
  await expect(page.getByRole('heading', { name: 'Experiment Library', exact: true })).toBeVisible()
  await expect(page).toHaveTitle('Experiment Library · AAMS-X')
  await trigger.click()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(trigger).toBeFocused()
  await page.keyboard.press('Control+k')
  await expect(search).toBeFocused()
  await search.fill('architecture')
  await search.press('Enter')
  await expect(page.getByRole('heading', { name: 'The intelligence loop' })).toBeVisible()
})

test('guided demo loads a real replay and supports chapters and focus view', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await expect(page.getByText('LOCAL ENGINE ONLINE')).toBeVisible()
  await page.getByRole('button', { name: 'Guided demo', exact: true }).click()
  const guide = page.getByRole('region', { name: 'Guided demo' })
  await expect(guide).toBeVisible()
  await expect(page.getByRole('slider', { name: 'Replay timeline', exact: true })).not.toHaveValue('0')
  await expect(page.getByText('RECORDED REPRODUCIBLE EXPERIMENT REPLAY', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Enter focus view' }).click()
  await expect(page.getByRole('navigation', { name: 'Main navigation' })).not.toBeVisible()
  await guide.getByRole('button', { name: 'Next chapter' }).click()
  await expect(page.getByRole('heading', { name: 'What the AI knows' })).toBeVisible()
  await guide.getByRole('button', { name: /Go to demo step 4:/ }).click()
  await expect(page.getByRole('heading', { name: 'Data Integrity & Provenance' })).toBeVisible()
  await page.getByRole('button', { name: 'Exit focus view' }).click()
  await expect(page.getByRole('navigation', { name: 'Main navigation' })).toBeVisible()
  await guide.getByRole('button', { name: 'End guided demo' }).click()
  await expect(guide).toHaveCount(0)
  expect(errors).toEqual([])
})

test('mobile navigation traps focus and closes with Escape without overflow', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await expect(page.getByText('LOCAL ENGINE ONLINE')).toBeVisible()
  const trigger = page.getByRole('button', { name: 'Open navigation', exact: true })
  await trigger.click()
  await expect(page.getByRole('dialog', { name: 'Navigation' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Close navigation panel' })).toBeFocused()
  await page.keyboard.press('Shift+Tab')
  await expect(page.getByRole('button', { name: 'Inspect architecture' })).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(page.getByRole('button', { name: 'Close navigation panel' })).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(trigger).toBeFocused()
  await expect(page.getByRole('navigation', { name: 'Main navigation' })).not.toBeVisible()
  await trigger.click()
  await page.getByRole('button', { name: 'Experiment Library', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Experiment Library', exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})
