name: Build Azure demo image
on:
  workflow_dispatch:
permissions:
  contents: read
  id-token: write
jobs:
  image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: azure/login@v2
        with:
          client-id: a73e66dd-5094-4d8e-9df1-897ef17b4ea4
          tenant-id: 255b4ffc-02da-4748-9e1b-7492977647d4
          subscription-id: 730856d9-ab78-4475-8ae5-2afa21bcde3e
      - run: az acr login --name caf851fd20faacr
      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            caf851fd20faacr.azurecr.io/aams-x:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
